services:
  dms-core:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
    
    # Enable GPU access (crucial for YOLO and ONNX)
    runtime: nvidia
    
    # Map the browser stream port (Container:Host)
    ports:
      - "5000:5000"
    
    # Persist data outside the container
    volumes:
      # Map the host 'logs' folder to the container's '/app/logs'
      - ./logs:/app/logs
      # Map the host 'models' folder to the container's '/app/models'
      - ./models:/app/models
      
    # Hardware Access Setup
    privileged: true
    devices:
      # Mount the I2C bus so the MPU6050 can connect
      - "/dev/i2c-1:/dev/i2c-1"
      - "/dev/i2c-0:/dev/i2c-0"
      # If we are using a USB webcam,
      - "/dev/video0:/dev/video0"
      # sound devices for the USB Speaker
      - "/dev/snd:/dev/snd"
    # Ensure it restarts automatically if it crashes
    restart: unless-stopped